# Set main site information.
title: Joseph U. Taylor
position: Robotics M.S.
affiliation: University of Michigan
email: joesphut (at) umich.edu

# Set seach engine optimization parameters.
keywords: Joseph Taylor Robotics Umich Michigan Urquhart
description: Joseph Taylor's personal website

# Set personal links.
cv_link:
github_link: https://github.com/JosephUT
linkedin: https://www.linkedin.com/in/joseph-taylor-052544238/

# Set image links.
avatar: ./assets/img/joseph3.jpg
favicon: ./assets/img/favicon.png

# Build subpages for every file under /_pages.
include:
  - _pages

# Add specific pages to the navigation bar.
navigation:
  - title: Projects
    url: /projects/
  - title: Teaching
    url: /teaching/
  - title: Posts
    url: /posts/
  - title: Resources
    url: /resources/

# Exclude unnecessary files.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# Set remote theme (heavily modified).
remote_theme: yaoyao-liu/minimal-light